/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tienda_wcf;

import com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author ismael
 */
public class tienda extends javax.swing.JFrame {

    public static String disco;
    public static String fuente;
    public static String pantalla;
    public static String procesador;
    public static String ram;
    public static String tarjeta;
    public static int precio;
    
    boolean marca=false;
    
    public tienda() {
        initComponents();
        
        //llenar nombres
        String nombredisco= selectDisco();
        //String nombredisco = selectDisco(); 
        System.out.println(nombredisco);
          
        //Cbox_disco.addItem("f");
        //marca=true;   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Cbox_disco = new javax.swing.JComboBox<>();
        Cbox_fuente = new javax.swing.JComboBox<>();
        Cbox_pantalla = new javax.swing.JComboBox<>();
        Cbox_procesador = new javax.swing.JComboBox<>();
        Cbox_ram = new javax.swing.JComboBox<>();
        Cbox_tarjeta = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_comprar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lbl_precio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Disco duro:");

        jLabel2.setText("Fuente de poder:");

        jLabel3.setText("Pantalla:");

        jLabel4.setText("Procesador:");

        jLabel5.setText("Memoria RAM:");

        jLabel6.setText("Tarjeta madre:");

        Cbox_disco.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Cbox_discoItemStateChanged(evt);
            }
        });

        Cbox_fuente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Cbox_fuenteItemStateChanged(evt);
            }
        });

        Cbox_pantalla.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Cbox_pantallaItemStateChanged(evt);
            }
        });

        Cbox_procesador.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Cbox_procesadorItemStateChanged(evt);
            }
        });

        Cbox_ram.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Cbox_ramItemStateChanged(evt);
            }
        });

        Cbox_tarjeta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Cbox_tarjetaItemStateChanged(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Descripcion", "Cantidad", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btn_comprar.setText("Comprar");
        btn_comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_comprarActionPerformed(evt);
            }
        });

        jLabel7.setText("Precio Total:");

        lbl_precio.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(49, 49, 49)
                        .addComponent(Cbox_disco, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_comprar)
                            .addGap(115, 115, 115)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_precio)
                            .addComponent(Cbox_tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cbox_ram, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cbox_procesador, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cbox_pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cbox_fuente, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(Cbox_disco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Cbox_fuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Cbox_pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Cbox_procesador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Cbox_ram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Cbox_tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbl_precio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_comprar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_comprarActionPerformed
        
        
        disco=Cbox_disco.getSelectedItem().toString();
        fuente=Cbox_fuente.getSelectedItem().toString();
        pantalla=Cbox_pantalla.getSelectedItem().toString();
        procesador=Cbox_procesador.getSelectedItem().toString();
        ram=Cbox_ram.getSelectedItem().toString();
        tarjeta=Cbox_tarjeta.getSelectedItem().toString();
        
        pago p=new pago();
        p.show();
        this.hide();
        
    }//GEN-LAST:event_btn_comprarActionPerformed

    private void Cbox_discoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Cbox_discoItemStateChanged
        if(marca=true){
        disco=Cbox_disco.getSelectedItem().toString();
        fuente=Cbox_fuente.getSelectedItem().toString();
        pantalla=Cbox_pantalla.getSelectedItem().toString();
        procesador=Cbox_procesador.getSelectedItem().toString();
        ram=Cbox_ram.getSelectedItem().toString();
        tarjeta=Cbox_tarjeta.getSelectedItem().toString();
        
        int resultado;
        
        resultado=calcularPrecio(disco, fuente, pantalla, procesador, ram, tarjeta);
        lbl_precio.setText(""+resultado+"");
        }
        
        else
        {
            System.out.println("nada");    
        }
        
        
        
        
    }//GEN-LAST:event_Cbox_discoItemStateChanged

    private void Cbox_fuenteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Cbox_fuenteItemStateChanged
        if(marca=true){
        disco=Cbox_disco.getSelectedItem().toString();
        fuente=Cbox_fuente.getSelectedItem().toString();
        pantalla=Cbox_pantalla.getSelectedItem().toString();
        procesador=Cbox_procesador.getSelectedItem().toString();
        ram=Cbox_ram.getSelectedItem().toString();
        tarjeta=Cbox_tarjeta.getSelectedItem().toString();
        
        int resultado;
        
        resultado=calcularPrecio(disco, fuente, pantalla, procesador, ram, tarjeta);
        lbl_precio.setText(""+resultado+"");    
        }
        
        
        
    }//GEN-LAST:event_Cbox_fuenteItemStateChanged

    private void Cbox_pantallaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Cbox_pantallaItemStateChanged
        if(marca=true){
        disco=Cbox_disco.getSelectedItem().toString();
        fuente=Cbox_fuente.getSelectedItem().toString();
        pantalla=Cbox_pantalla.getSelectedItem().toString();
        procesador=Cbox_procesador.getSelectedItem().toString();
        ram=Cbox_ram.getSelectedItem().toString();
        tarjeta=Cbox_tarjeta.getSelectedItem().toString();
        
        int resultado;
        
        resultado=calcularPrecio(disco, fuente, pantalla, procesador, ram, tarjeta);
        lbl_precio.setText(""+resultado+"");    
        }
        
        
        
        
    }//GEN-LAST:event_Cbox_pantallaItemStateChanged

    private void Cbox_procesadorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Cbox_procesadorItemStateChanged
        if(marca=true){
        disco=Cbox_disco.getSelectedItem().toString();
        fuente=Cbox_fuente.getSelectedItem().toString();
        pantalla=Cbox_pantalla.getSelectedItem().toString();
        procesador=Cbox_procesador.getSelectedItem().toString();
        ram=Cbox_ram.getSelectedItem().toString();
        tarjeta=Cbox_tarjeta.getSelectedItem().toString();
        
        int resultado;
        
        resultado=calcularPrecio(disco, fuente, pantalla, procesador, ram, tarjeta);
        lbl_precio.setText(""+resultado+"");
        }
        
        
        
        
    }//GEN-LAST:event_Cbox_procesadorItemStateChanged

    private void Cbox_ramItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Cbox_ramItemStateChanged
        if(marca=true){
        disco=Cbox_disco.getSelectedItem().toString();
        fuente=Cbox_fuente.getSelectedItem().toString();
        pantalla=Cbox_pantalla.getSelectedItem().toString();
        procesador=Cbox_procesador.getSelectedItem().toString();
        ram=Cbox_ram.getSelectedItem().toString();
        tarjeta=Cbox_tarjeta.getSelectedItem().toString();
        
        int resultado;
        
        resultado=calcularPrecio(disco, fuente, pantalla, procesador, ram, tarjeta);
        lbl_precio.setText(""+resultado+"");
        }
        
        
        
        
    }//GEN-LAST:event_Cbox_ramItemStateChanged

    private void Cbox_tarjetaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Cbox_tarjetaItemStateChanged
        if(marca=true){
        disco=Cbox_disco.getSelectedItem().toString();
        fuente=Cbox_fuente.getSelectedItem().toString();
        pantalla=Cbox_pantalla.getSelectedItem().toString();
        procesador=Cbox_procesador.getSelectedItem().toString();
        ram=Cbox_ram.getSelectedItem().toString();
        tarjeta=Cbox_tarjeta.getSelectedItem().toString();
        
        int resultado;
        
        resultado=calcularPrecio(disco, fuente, pantalla, procesador, ram, tarjeta);
        lbl_precio.setText(""+resultado+"");
        }
        
        
        
        
    }//GEN-LAST:event_Cbox_tarjetaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cbox_disco;
    private javax.swing.JComboBox<String> Cbox_fuente;
    private javax.swing.JComboBox<String> Cbox_pantalla;
    private javax.swing.JComboBox<String> Cbox_procesador;
    private javax.swing.JComboBox<String> Cbox_ram;
    private javax.swing.JComboBox<String> Cbox_tarjeta;
    private javax.swing.JButton btn_comprar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_precio;
    // End of variables declaration//GEN-END:variables

    private static int calcularPrecio(java.lang.String nomDisc, java.lang.String nomFuente, java.lang.String nomPantalla, java.lang.String nomProcesador, java.lang.String nomRam, java.lang.String nomTarjeta) {
        int resultado;
        org.tempuri.Service1 service = new org.tempuri.Service1();
        org.tempuri.IService1 port = service.getBasicHttpBindingIService1();
        resultado=port.calcularPrecio(nomDisc, nomFuente, nomPantalla, nomProcesador, nomRam, nomTarjeta);
        return resultado;
    }

    

    private static String selectFuente() {
        org.tempuri.Service1 service = new org.tempuri.Service1();
        org.tempuri.IService1 port = service.getBasicHttpBindingIService1();
        return port.selectFuente();
    }

    private static String selectPantalla() {
        org.tempuri.Service1 service = new org.tempuri.Service1();
        org.tempuri.IService1 port = service.getBasicHttpBindingIService1();
        return port.selectPantalla();
    }

    private static String selectProcesador() {
        org.tempuri.Service1 service = new org.tempuri.Service1();
        org.tempuri.IService1 port = service.getBasicHttpBindingIService1();
        return port.selectProcesador();
    }

    private static String selectRam() {
        org.tempuri.Service1 service = new org.tempuri.Service1();
        org.tempuri.IService1 port = service.getBasicHttpBindingIService1();
        return port.selectRam();
    }

    private static String selectTarjeta() {
        org.tempuri.Service1 service = new org.tempuri.Service1();
        org.tempuri.IService1 port = service.getBasicHttpBindingIService1();
        return port.selectTarjeta();
    }

    private static String selectDisco() {
        org.tempuri.Service1 service = new org.tempuri.Service1();
        org.tempuri.IService1 port = service.getBasicHttpBindingIService1();
        return port.selectDisco();
    }

    
}
