//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Admi.Proxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="articulos", Namespace="http://schemas.datacontract.org/2004/07/Data")]
    [System.SerializableAttribute()]
    public partial class articulos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PrecioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Proxy.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/compra", ReplyAction="http://tempuri.org/IService1/compraResponse")]
        int compra(string num_tarjeta, string fecha, string num_seguridad, string nom_disc, string nom_fuente, string nom_pantalla, string nom_procesador, string nom_ram, string nom_tarjeta, int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/compra", ReplyAction="http://tempuri.org/IService1/compraResponse")]
        System.Threading.Tasks.Task<int> compraAsync(string num_tarjeta, string fecha, string num_seguridad, string nom_disc, string nom_fuente, string nom_pantalla, string nom_procesador, string nom_ram, string nom_tarjeta, int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/calcular_precio", ReplyAction="http://tempuri.org/IService1/calcular_precioResponse")]
        int calcular_precio(string nom_disc, string nom_fuente, string nom_pantalla, string nom_procesador, string nom_ram, string nom_tarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/calcular_precio", ReplyAction="http://tempuri.org/IService1/calcular_precioResponse")]
        System.Threading.Tasks.Task<int> calcular_precioAsync(string nom_disc, string nom_fuente, string nom_pantalla, string nom_procesador, string nom_ram, string nom_tarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/login", ReplyAction="http://tempuri.org/IService1/loginResponse")]
        int login(string id, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/login", ReplyAction="http://tempuri.org/IService1/loginResponse")]
        System.Threading.Tasks.Task<int> loginAsync(string id, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delete_fuente", ReplyAction="http://tempuri.org/IService1/delete_fuenteResponse")]
        int delete_fuente(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delete_fuente", ReplyAction="http://tempuri.org/IService1/delete_fuenteResponse")]
        System.Threading.Tasks.Task<int> delete_fuenteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delete_disco", ReplyAction="http://tempuri.org/IService1/delete_discoResponse")]
        int delete_disco(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delete_disco", ReplyAction="http://tempuri.org/IService1/delete_discoResponse")]
        System.Threading.Tasks.Task<int> delete_discoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delete_pantalla", ReplyAction="http://tempuri.org/IService1/delete_pantallaResponse")]
        int delete_pantalla(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delete_pantalla", ReplyAction="http://tempuri.org/IService1/delete_pantallaResponse")]
        System.Threading.Tasks.Task<int> delete_pantallaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delete_procesador", ReplyAction="http://tempuri.org/IService1/delete_procesadorResponse")]
        int delete_procesador(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delete_procesador", ReplyAction="http://tempuri.org/IService1/delete_procesadorResponse")]
        System.Threading.Tasks.Task<int> delete_procesadorAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delete_ram", ReplyAction="http://tempuri.org/IService1/delete_ramResponse")]
        int delete_ram(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delete_ram", ReplyAction="http://tempuri.org/IService1/delete_ramResponse")]
        System.Threading.Tasks.Task<int> delete_ramAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delete_tarjeta", ReplyAction="http://tempuri.org/IService1/delete_tarjetaResponse")]
        int delete_tarjeta(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delete_tarjeta", ReplyAction="http://tempuri.org/IService1/delete_tarjetaResponse")]
        System.Threading.Tasks.Task<int> delete_tarjetaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insert_disco", ReplyAction="http://tempuri.org/IService1/insert_discoResponse")]
        int insert_disco(string nombre, string descripcion, int cant, int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insert_disco", ReplyAction="http://tempuri.org/IService1/insert_discoResponse")]
        System.Threading.Tasks.Task<int> insert_discoAsync(string nombre, string descripcion, int cant, int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insert_fuente", ReplyAction="http://tempuri.org/IService1/insert_fuenteResponse")]
        int insert_fuente(string nombre, string descripcion, int cant, int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insert_fuente", ReplyAction="http://tempuri.org/IService1/insert_fuenteResponse")]
        System.Threading.Tasks.Task<int> insert_fuenteAsync(string nombre, string descripcion, int cant, int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insert_pantalla", ReplyAction="http://tempuri.org/IService1/insert_pantallaResponse")]
        int insert_pantalla(string nombre, string descripcion, int cant, int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insert_pantalla", ReplyAction="http://tempuri.org/IService1/insert_pantallaResponse")]
        System.Threading.Tasks.Task<int> insert_pantallaAsync(string nombre, string descripcion, int cant, int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insert_procesador", ReplyAction="http://tempuri.org/IService1/insert_procesadorResponse")]
        int insert_procesador(string nombre, string descripcion, int cant, int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insert_procesador", ReplyAction="http://tempuri.org/IService1/insert_procesadorResponse")]
        System.Threading.Tasks.Task<int> insert_procesadorAsync(string nombre, string descripcion, int cant, int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insert_ram", ReplyAction="http://tempuri.org/IService1/insert_ramResponse")]
        int insert_ram(string nombre, string descripcion, int cant, int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insert_ram", ReplyAction="http://tempuri.org/IService1/insert_ramResponse")]
        System.Threading.Tasks.Task<int> insert_ramAsync(string nombre, string descripcion, int cant, int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insert_tarjeta", ReplyAction="http://tempuri.org/IService1/insert_tarjetaResponse")]
        int insert_tarjeta(string nombre, string descripcion, int cant, int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insert_tarjeta", ReplyAction="http://tempuri.org/IService1/insert_tarjetaResponse")]
        System.Threading.Tasks.Task<int> insert_tarjetaAsync(string nombre, string descripcion, int cant, int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/update_disco", ReplyAction="http://tempuri.org/IService1/update_discoResponse")]
        int update_disco(int id, string nombre, string descripcion, int cant, int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/update_disco", ReplyAction="http://tempuri.org/IService1/update_discoResponse")]
        System.Threading.Tasks.Task<int> update_discoAsync(int id, string nombre, string descripcion, int cant, int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/update_fuente", ReplyAction="http://tempuri.org/IService1/update_fuenteResponse")]
        int update_fuente(int id, string nombre, string descripcion, int cant, int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/update_fuente", ReplyAction="http://tempuri.org/IService1/update_fuenteResponse")]
        System.Threading.Tasks.Task<int> update_fuenteAsync(int id, string nombre, string descripcion, int cant, int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/update_pantalla", ReplyAction="http://tempuri.org/IService1/update_pantallaResponse")]
        int update_pantalla(int id, string nombre, string descripcion, int cant, int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/update_pantalla", ReplyAction="http://tempuri.org/IService1/update_pantallaResponse")]
        System.Threading.Tasks.Task<int> update_pantallaAsync(int id, string nombre, string descripcion, int cant, int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/update_procesador", ReplyAction="http://tempuri.org/IService1/update_procesadorResponse")]
        int update_procesador(int id, string nombre, string descripcion, int cant, int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/update_procesador", ReplyAction="http://tempuri.org/IService1/update_procesadorResponse")]
        System.Threading.Tasks.Task<int> update_procesadorAsync(int id, string nombre, string descripcion, int cant, int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/update_ram", ReplyAction="http://tempuri.org/IService1/update_ramResponse")]
        int update_ram(int id, string nombre, string descripcion, int cant, int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/update_ram", ReplyAction="http://tempuri.org/IService1/update_ramResponse")]
        System.Threading.Tasks.Task<int> update_ramAsync(int id, string nombre, string descripcion, int cant, int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/update_tarjeta", ReplyAction="http://tempuri.org/IService1/update_tarjetaResponse")]
        int update_tarjeta(int id, string nombre, string descripcion, int cant, int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/update_tarjeta", ReplyAction="http://tempuri.org/IService1/update_tarjetaResponse")]
        System.Threading.Tasks.Task<int> update_tarjetaAsync(int id, string nombre, string descripcion, int cant, int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sf_disco", ReplyAction="http://tempuri.org/IService1/sf_discoResponse")]
        WCF_Admi.Proxy.articulos[] sf_disco();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sf_disco", ReplyAction="http://tempuri.org/IService1/sf_discoResponse")]
        System.Threading.Tasks.Task<WCF_Admi.Proxy.articulos[]> sf_discoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sf_fuente", ReplyAction="http://tempuri.org/IService1/sf_fuenteResponse")]
        WCF_Admi.Proxy.articulos[] sf_fuente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sf_fuente", ReplyAction="http://tempuri.org/IService1/sf_fuenteResponse")]
        System.Threading.Tasks.Task<WCF_Admi.Proxy.articulos[]> sf_fuenteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sf_pantalla", ReplyAction="http://tempuri.org/IService1/sf_pantallaResponse")]
        WCF_Admi.Proxy.articulos[] sf_pantalla();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sf_pantalla", ReplyAction="http://tempuri.org/IService1/sf_pantallaResponse")]
        System.Threading.Tasks.Task<WCF_Admi.Proxy.articulos[]> sf_pantallaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sf_procesador", ReplyAction="http://tempuri.org/IService1/sf_procesadorResponse")]
        WCF_Admi.Proxy.articulos[] sf_procesador();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sf_procesador", ReplyAction="http://tempuri.org/IService1/sf_procesadorResponse")]
        System.Threading.Tasks.Task<WCF_Admi.Proxy.articulos[]> sf_procesadorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sf_ram", ReplyAction="http://tempuri.org/IService1/sf_ramResponse")]
        WCF_Admi.Proxy.articulos[] sf_ram();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sf_ram", ReplyAction="http://tempuri.org/IService1/sf_ramResponse")]
        System.Threading.Tasks.Task<WCF_Admi.Proxy.articulos[]> sf_ramAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sf_tarjeta", ReplyAction="http://tempuri.org/IService1/sf_tarjetaResponse")]
        WCF_Admi.Proxy.articulos[] sf_tarjeta();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sf_tarjeta", ReplyAction="http://tempuri.org/IService1/sf_tarjetaResponse")]
        System.Threading.Tasks.Task<WCF_Admi.Proxy.articulos[]> sf_tarjetaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/select_disco", ReplyAction="http://tempuri.org/IService1/select_discoResponse")]
        string[] select_disco();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/select_disco", ReplyAction="http://tempuri.org/IService1/select_discoResponse")]
        System.Threading.Tasks.Task<string[]> select_discoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/select_fuente", ReplyAction="http://tempuri.org/IService1/select_fuenteResponse")]
        string[] select_fuente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/select_fuente", ReplyAction="http://tempuri.org/IService1/select_fuenteResponse")]
        System.Threading.Tasks.Task<string[]> select_fuenteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/select_pantalla", ReplyAction="http://tempuri.org/IService1/select_pantallaResponse")]
        string[] select_pantalla();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/select_pantalla", ReplyAction="http://tempuri.org/IService1/select_pantallaResponse")]
        System.Threading.Tasks.Task<string[]> select_pantallaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/select_procesador", ReplyAction="http://tempuri.org/IService1/select_procesadorResponse")]
        string[] select_procesador();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/select_procesador", ReplyAction="http://tempuri.org/IService1/select_procesadorResponse")]
        System.Threading.Tasks.Task<string[]> select_procesadorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/select_ram", ReplyAction="http://tempuri.org/IService1/select_ramResponse")]
        string[] select_ram();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/select_ram", ReplyAction="http://tempuri.org/IService1/select_ramResponse")]
        System.Threading.Tasks.Task<string[]> select_ramAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/select_tarjeta", ReplyAction="http://tempuri.org/IService1/select_tarjetaResponse")]
        string[] select_tarjeta();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/select_tarjeta", ReplyAction="http://tempuri.org/IService1/select_tarjetaResponse")]
        System.Threading.Tasks.Task<string[]> select_tarjetaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WCF_Admi.Proxy.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WCF_Admi.Proxy.IService1>, WCF_Admi.Proxy.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int compra(string num_tarjeta, string fecha, string num_seguridad, string nom_disc, string nom_fuente, string nom_pantalla, string nom_procesador, string nom_ram, string nom_tarjeta, int precio) {
            return base.Channel.compra(num_tarjeta, fecha, num_seguridad, nom_disc, nom_fuente, nom_pantalla, nom_procesador, nom_ram, nom_tarjeta, precio);
        }
        
        public System.Threading.Tasks.Task<int> compraAsync(string num_tarjeta, string fecha, string num_seguridad, string nom_disc, string nom_fuente, string nom_pantalla, string nom_procesador, string nom_ram, string nom_tarjeta, int precio) {
            return base.Channel.compraAsync(num_tarjeta, fecha, num_seguridad, nom_disc, nom_fuente, nom_pantalla, nom_procesador, nom_ram, nom_tarjeta, precio);
        }
        
        public int calcular_precio(string nom_disc, string nom_fuente, string nom_pantalla, string nom_procesador, string nom_ram, string nom_tarjeta) {
            return base.Channel.calcular_precio(nom_disc, nom_fuente, nom_pantalla, nom_procesador, nom_ram, nom_tarjeta);
        }
        
        public System.Threading.Tasks.Task<int> calcular_precioAsync(string nom_disc, string nom_fuente, string nom_pantalla, string nom_procesador, string nom_ram, string nom_tarjeta) {
            return base.Channel.calcular_precioAsync(nom_disc, nom_fuente, nom_pantalla, nom_procesador, nom_ram, nom_tarjeta);
        }
        
        public int login(string id, string pass) {
            return base.Channel.login(id, pass);
        }
        
        public System.Threading.Tasks.Task<int> loginAsync(string id, string pass) {
            return base.Channel.loginAsync(id, pass);
        }
        
        public int delete_fuente(int id) {
            return base.Channel.delete_fuente(id);
        }
        
        public System.Threading.Tasks.Task<int> delete_fuenteAsync(int id) {
            return base.Channel.delete_fuenteAsync(id);
        }
        
        public int delete_disco(int id) {
            return base.Channel.delete_disco(id);
        }
        
        public System.Threading.Tasks.Task<int> delete_discoAsync(int id) {
            return base.Channel.delete_discoAsync(id);
        }
        
        public int delete_pantalla(int id) {
            return base.Channel.delete_pantalla(id);
        }
        
        public System.Threading.Tasks.Task<int> delete_pantallaAsync(int id) {
            return base.Channel.delete_pantallaAsync(id);
        }
        
        public int delete_procesador(int id) {
            return base.Channel.delete_procesador(id);
        }
        
        public System.Threading.Tasks.Task<int> delete_procesadorAsync(int id) {
            return base.Channel.delete_procesadorAsync(id);
        }
        
        public int delete_ram(int id) {
            return base.Channel.delete_ram(id);
        }
        
        public System.Threading.Tasks.Task<int> delete_ramAsync(int id) {
            return base.Channel.delete_ramAsync(id);
        }
        
        public int delete_tarjeta(int id) {
            return base.Channel.delete_tarjeta(id);
        }
        
        public System.Threading.Tasks.Task<int> delete_tarjetaAsync(int id) {
            return base.Channel.delete_tarjetaAsync(id);
        }
        
        public int insert_disco(string nombre, string descripcion, int cant, int precio) {
            return base.Channel.insert_disco(nombre, descripcion, cant, precio);
        }
        
        public System.Threading.Tasks.Task<int> insert_discoAsync(string nombre, string descripcion, int cant, int precio) {
            return base.Channel.insert_discoAsync(nombre, descripcion, cant, precio);
        }
        
        public int insert_fuente(string nombre, string descripcion, int cant, int precio) {
            return base.Channel.insert_fuente(nombre, descripcion, cant, precio);
        }
        
        public System.Threading.Tasks.Task<int> insert_fuenteAsync(string nombre, string descripcion, int cant, int precio) {
            return base.Channel.insert_fuenteAsync(nombre, descripcion, cant, precio);
        }
        
        public int insert_pantalla(string nombre, string descripcion, int cant, int precio) {
            return base.Channel.insert_pantalla(nombre, descripcion, cant, precio);
        }
        
        public System.Threading.Tasks.Task<int> insert_pantallaAsync(string nombre, string descripcion, int cant, int precio) {
            return base.Channel.insert_pantallaAsync(nombre, descripcion, cant, precio);
        }
        
        public int insert_procesador(string nombre, string descripcion, int cant, int precio) {
            return base.Channel.insert_procesador(nombre, descripcion, cant, precio);
        }
        
        public System.Threading.Tasks.Task<int> insert_procesadorAsync(string nombre, string descripcion, int cant, int precio) {
            return base.Channel.insert_procesadorAsync(nombre, descripcion, cant, precio);
        }
        
        public int insert_ram(string nombre, string descripcion, int cant, int precio) {
            return base.Channel.insert_ram(nombre, descripcion, cant, precio);
        }
        
        public System.Threading.Tasks.Task<int> insert_ramAsync(string nombre, string descripcion, int cant, int precio) {
            return base.Channel.insert_ramAsync(nombre, descripcion, cant, precio);
        }
        
        public int insert_tarjeta(string nombre, string descripcion, int cant, int precio) {
            return base.Channel.insert_tarjeta(nombre, descripcion, cant, precio);
        }
        
        public System.Threading.Tasks.Task<int> insert_tarjetaAsync(string nombre, string descripcion, int cant, int precio) {
            return base.Channel.insert_tarjetaAsync(nombre, descripcion, cant, precio);
        }
        
        public int update_disco(int id, string nombre, string descripcion, int cant, int precio) {
            return base.Channel.update_disco(id, nombre, descripcion, cant, precio);
        }
        
        public System.Threading.Tasks.Task<int> update_discoAsync(int id, string nombre, string descripcion, int cant, int precio) {
            return base.Channel.update_discoAsync(id, nombre, descripcion, cant, precio);
        }
        
        public int update_fuente(int id, string nombre, string descripcion, int cant, int precio) {
            return base.Channel.update_fuente(id, nombre, descripcion, cant, precio);
        }
        
        public System.Threading.Tasks.Task<int> update_fuenteAsync(int id, string nombre, string descripcion, int cant, int precio) {
            return base.Channel.update_fuenteAsync(id, nombre, descripcion, cant, precio);
        }
        
        public int update_pantalla(int id, string nombre, string descripcion, int cant, int precio) {
            return base.Channel.update_pantalla(id, nombre, descripcion, cant, precio);
        }
        
        public System.Threading.Tasks.Task<int> update_pantallaAsync(int id, string nombre, string descripcion, int cant, int precio) {
            return base.Channel.update_pantallaAsync(id, nombre, descripcion, cant, precio);
        }
        
        public int update_procesador(int id, string nombre, string descripcion, int cant, int precio) {
            return base.Channel.update_procesador(id, nombre, descripcion, cant, precio);
        }
        
        public System.Threading.Tasks.Task<int> update_procesadorAsync(int id, string nombre, string descripcion, int cant, int precio) {
            return base.Channel.update_procesadorAsync(id, nombre, descripcion, cant, precio);
        }
        
        public int update_ram(int id, string nombre, string descripcion, int cant, int precio) {
            return base.Channel.update_ram(id, nombre, descripcion, cant, precio);
        }
        
        public System.Threading.Tasks.Task<int> update_ramAsync(int id, string nombre, string descripcion, int cant, int precio) {
            return base.Channel.update_ramAsync(id, nombre, descripcion, cant, precio);
        }
        
        public int update_tarjeta(int id, string nombre, string descripcion, int cant, int precio) {
            return base.Channel.update_tarjeta(id, nombre, descripcion, cant, precio);
        }
        
        public System.Threading.Tasks.Task<int> update_tarjetaAsync(int id, string nombre, string descripcion, int cant, int precio) {
            return base.Channel.update_tarjetaAsync(id, nombre, descripcion, cant, precio);
        }
        
        public WCF_Admi.Proxy.articulos[] sf_disco() {
            return base.Channel.sf_disco();
        }
        
        public System.Threading.Tasks.Task<WCF_Admi.Proxy.articulos[]> sf_discoAsync() {
            return base.Channel.sf_discoAsync();
        }
        
        public WCF_Admi.Proxy.articulos[] sf_fuente() {
            return base.Channel.sf_fuente();
        }
        
        public System.Threading.Tasks.Task<WCF_Admi.Proxy.articulos[]> sf_fuenteAsync() {
            return base.Channel.sf_fuenteAsync();
        }
        
        public WCF_Admi.Proxy.articulos[] sf_pantalla() {
            return base.Channel.sf_pantalla();
        }
        
        public System.Threading.Tasks.Task<WCF_Admi.Proxy.articulos[]> sf_pantallaAsync() {
            return base.Channel.sf_pantallaAsync();
        }
        
        public WCF_Admi.Proxy.articulos[] sf_procesador() {
            return base.Channel.sf_procesador();
        }
        
        public System.Threading.Tasks.Task<WCF_Admi.Proxy.articulos[]> sf_procesadorAsync() {
            return base.Channel.sf_procesadorAsync();
        }
        
        public WCF_Admi.Proxy.articulos[] sf_ram() {
            return base.Channel.sf_ram();
        }
        
        public System.Threading.Tasks.Task<WCF_Admi.Proxy.articulos[]> sf_ramAsync() {
            return base.Channel.sf_ramAsync();
        }
        
        public WCF_Admi.Proxy.articulos[] sf_tarjeta() {
            return base.Channel.sf_tarjeta();
        }
        
        public System.Threading.Tasks.Task<WCF_Admi.Proxy.articulos[]> sf_tarjetaAsync() {
            return base.Channel.sf_tarjetaAsync();
        }
        
        public string[] select_disco() {
            return base.Channel.select_disco();
        }
        
        public System.Threading.Tasks.Task<string[]> select_discoAsync() {
            return base.Channel.select_discoAsync();
        }
        
        public string[] select_fuente() {
            return base.Channel.select_fuente();
        }
        
        public System.Threading.Tasks.Task<string[]> select_fuenteAsync() {
            return base.Channel.select_fuenteAsync();
        }
        
        public string[] select_pantalla() {
            return base.Channel.select_pantalla();
        }
        
        public System.Threading.Tasks.Task<string[]> select_pantallaAsync() {
            return base.Channel.select_pantallaAsync();
        }
        
        public string[] select_procesador() {
            return base.Channel.select_procesador();
        }
        
        public System.Threading.Tasks.Task<string[]> select_procesadorAsync() {
            return base.Channel.select_procesadorAsync();
        }
        
        public string[] select_ram() {
            return base.Channel.select_ram();
        }
        
        public System.Threading.Tasks.Task<string[]> select_ramAsync() {
            return base.Channel.select_ramAsync();
        }
        
        public string[] select_tarjeta() {
            return base.Channel.select_tarjeta();
        }
        
        public System.Threading.Tasks.Task<string[]> select_tarjetaAsync() {
            return base.Channel.select_tarjetaAsync();
        }
    }
}
